services:
  - type: web
    name: onlineexamportal-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://cutmap.netlify.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,PATCH,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization,X-Requested-With,Cookie
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true" 